### ISSUE TITLE
Introduce reactive hydra client to avoid callback hell

### ISSUE THREAD

**Issue by matiwinnetou** [cardano-foundation/hydra-java#22]
Currently hydra level client is 'classic' in a sense that it uses listeners to notify about events. We would like to introduce another module to this project based on JDK9 or project react / RxJava which makes it easier to work with even based system based on callbacks by introducing more high level data structures (e.g. Mono, Flux, CompletableFuture, Publisher, etc).

**Comment by the-vj** [comment]
would the new java virtual threads (JDK21) be of any use instead? i.e. turning the paradigm on its head again - elementary synchronous code on the outside for coding simplicity, with native support of asynchronous processing hidden under the hood, without the need for additional frameworks?

**Comment by matiwinnetou** [comment]
Yes, Project Loom is a game changer and we would need to revisit how much it makes sense.

In resource consumption sense post JDK 21 it doesn't make sense anymore, it could make sense in a way to manage an asychronous flow, which is arguably harder with traditional mutexes, semaphores, barries, etc.

Biggest challenge I see in Hydra is not resource constraints as we are dealing with a blockchain here (hence strong consensus systems) but rather in a sense to make it easier to manage asynchronous flows.

**Comment by matiwinnetou** [comment]
#41

**Comment by matiwinnetou** [comment]
Generally it is working but needs to be iterated on and integration tests added for it.

There maybe some scenarios still uncovered, new module: hydra-java-reactive-reactor-client
